### ISSUE TITLE
Add path filter to workflows?

### ISSUE THREAD

**Issue by garrettw** [MbinOrg/mbin#1336]
**Is your feature request related to a problem? Please describe.**
It would be nice if the workflow that runs unit tests would only run if PHP or Composer files have changed in a given PR.

**Describe the solution you'd like**
I’d like to add path filters to the workflow to keep it from running if relevant files haven’t changed.

**Describe alternatives you've considered**
None

**Additional context**
Getting unit tests to run in parallel would help it to be less of a blocker, but it would still take time to run that might could be avoided.

**Comment by melroy89** [comment]
Unit tests are actually running within 5 seconds :).

It's the integration tests that take longer. However BentiGorlich recently combined the two into a single workflow: https://github.com/MbinOrg/mbin/pull/1300#issuecomment-2562496338. 

But yes the integration test is running for like 22 mins. On Matrix chat we were already discussion to get it paratest working in the future. But again the issue is NOT unit tests, the issue is integration tests which takes 99% of the time.

There is often no easy way to determine whether or not you will need to run integration (or unit) test for a specific file changed. However, we could maybe come-up with a plan to skip the integration on PRs of the `src` directory is not changed. Something like that. And always run integration tests on the main branch.

**Comment by garrettw** [comment]
My mistake, I meant integration tests.
My thought was to only run it if src/ or composer.* changes.

**Comment by melroy89** [comment]
Yes makes sense to me. And just be sure always run it on the main branch as well?

**Comment by garrettw** [comment]
As opposed to … running it on PRs?
I like it running on PRs.

**Comment by melroy89** [comment]
Always run it on the main branch. And only run it on PRs in case of changes, is what I mean to say.

**Comment by garrettw** [comment]
Ah ok, I think I understand now. Apply path filters to PR runs only.

**Comment by garrettw** [comment]
I was just looking through the docs about path filters, and I found this:
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-paths

> If a workflow is skipped due to path filtering ... then checks associated with that workflow will remain in a "Pending" state. **A pull request that requires those checks to be successful will be blocked from merging.**

So for this to work, the automated-tests job would have to be set as not required. Hmm... thoughts?
(It would still run automatically, but it wouldn't block merging if it failed.)

**Comment by melroy89** [comment]
Split the workflow again like it was. Create a separate workflow for integration test. Making this workflow optional. While the unit test is always required.

**Comment by BentiGorlich** [comment]
I don't think that we should consider not marking the integration tests as required... If there is no way to do it, then I'd just not do it...

**Comment by melroy89** [comment]
> I don't think that we should consider not marking the integration tests as required...

Double negative.. Which makes it very hard to understand it for me 😖 . You mean, you do want to keep integration tests required?

**Comment by garrettw** [comment]
Yes, I think that’s what he meant, and I can understand that position and I anticipated it. That’s why I mentioned a workaround.

**Comment by melroy89** [comment]
You can skip steps in a workflow yes. Using a `if`: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution

**Comment by garrettw** [comment]
Oh, this is good info. Thanks, I’ll look over it.

**Comment by melroy89** [comment]
Great! Also.. you can use a previous step to determine whether or not to run the integration test and use for example "an output parameter": https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-output-parameter. 

When you then use in the follow-up `if` step to continue or skip the step.

**Comment by garrettw** [comment]
This is proving to be challenging 😅

I do have a question about how we want to handle this. Let me lay out a scenario:

- PR is created with commits that change PHP files
- Integration tests run, as they’re supposed to
- A new commit is pushed to the source branch that only contains changes to non-PHP files

Should we:
1. Run the integration tests again because PHP files are changed in another commit in the PR?
2. Skip the integration tests this time because the most recent push did not change PHP files?

**Comment by melroy89** [comment]
> This is proving to be challenging 😅
> 
> I do have a question about how we want to handle this. Let me lay out a scenario:
> 
>     * PR is created with commits that change PHP files
> 
>     * Integration tests run, as they’re supposed to
> 
>     * A new commit is pushed to the source branch that only contains changes to non-PHP files
> 
> 
> Should we:
> 
>     1. Run the integration tests again because PHP files are changed in another commit in the PR?
> 
>     2. Skip the integration tests this time because the most recent push did not change PHP files?

My logical answer would be option 2.

**Comment by garrettw** [comment]
Of course this partly depends on what info is easiest to access about the event triggering the test run. I am debugging that on a different PR right now.
So far, I have found the following:
- On a `pull_request` event, `github.head_ref` contains the source branch name, and `github.base_ref` contains the target branch name.

I still need to debug a `push` event.

**Comment by melroy89** [comment]
I see.. Hm, maybe we are making it unnecessary complex for us.  What about: https://github.com/marketplace/actions/changed-files?


Example from above link:

```yaml
on:
  pull_request:
    branches:
      - main

jobs:
  # -------------------------------------------------------------
  # Event `pull_request`: Returns all changed pull request files.
  # --------------------------------------------------------------
  changed_files:
    # NOTE:
    # - This is limited to pull_request* events and would raise an error for other events.
    # - A maximum of 3000 files can be returned.
    # - For more flexibility and no limitations see "Using local .git directory" above.

    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
```


We can also check for only **PHP files** that are changed in the **`src` directory**, using (didn't test it):

```yaml
      - name: Get all src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            src:
              - src/**.php
```

Outputs we could leverage, could be: [`modified_keys`](https://github.com/marketplace/actions/changed-files#output_modified_keys).
